export const FETCH_FILMS_START = "FETCH_FILMS_START";
export const FETCH_FILMS_SUCCESS = "FETCH_FILMS_SUCCESS";
export const FETCH_FILMS_FAILURE = "FETCH_FILMS_FAILURE";

export const FETCH_FILM_ABOUT = "FETCH_FILM_ABOUT";

export const FETCH_GENRES_START = "FETCH_GENRES_START";
export const FETCH_GENRES_SUCCESS = "FETCH_GENRES_SUCCESS";
export const FETCH_GENRES_FAILURE = "FETCH_GENRES_FAILURE";

export const SET_FILTER = "SET_FILTER";
export const RESET_FILTER = "RESET_FILTER";
export const SET_SEARCH_WORD = "SET_SEARCH_WORD";

export const TOGGLE_FAVORITE = "TOGGLE_FAVORITE";
export const REMOVE_FAVORITE_FILM = "REMOVE_TOGGLE_FAVORITE";

export const RESET_PAGINATION = "RESET_PAGINATION";
