export const FETCH_ACTORS_START = "FETCH_ACTORS_START";
export const FETCH_ACTORS_SUCCESS = "FETCH_ACTORS_SUCCESS";
export const FETCH_ACTORS_FAILURE = "FETCH_ACTORS_FAILURE";

export const GET_ACTOR_DESCRIPTION = "GET_ACTOR_DESCRIPTION";

export const SET_QUERY_WORD = "SET_QUERY_WORD";

export const CHANGE_PAGE = "CHANGE_PAGE";
